= +plast+ — Modular Threat Hunting Tool & Framework
Nelson "sk4la" Cornet <https://github.com/sk4la>
:uri-repo: https://github.com/sk4la/plast
:uri-license: {uri-repo}/blob/master/LICENSE.adoc
:uri-readme: {uri-repo}/blob/master/README.adoc

image:https://img.shields.io/badge/python-3.7-blue.svg[link={uri-python}] image:https://img.shields.io/badge/license-MIT-green.svg[link={uri-license}]

== Getting Started

Hmmm, {uri-readme}[what's this project about?].

Please refer to the instructions in {uri-license}[README.adoc] to install the latest version of the project.

== Contributing

The `plast` project can only be useful if there are modules helping to process custom data formats.

Following this direction, the framework allows to easily integrate new modules by creating custom classes and simply dropping them in the `framework/modules/*` directories. That's it.

=== Writing custom modules

The core process is handled by three main classes defined in the `framework.contexts.models` module. This module defines the three `Pre`, `Post` and `Callback` reference classes.

Modules *must* inherit from one of these reference classes:

* `Pre` (or _preprocessing_) modules are meant to handle the data *before* the engine starts scanning evidence(s). Only one `Pre` module can be invoked _per_ `plast` instance since this type of module corresponds to a positional command-line argument (e.g. `plast -o out file -i sample.pdf`).
* `Post` (or _postprocessing_) modules are designed to process the match(es) yielded by the engine. Multiple `Post` modules can be called using the `--post` argument (e.g. `plast -o out --post banana apple orange file -i sample.pdf`). These modules are invoked one after the other so these can be chained at will. The invocation sequence respects the order given by the `--post` argument.
* `Callback` modules are a second way to handle the match(es) issued by the engine. Sometimes, during large matching campaigns, postprocessing the matches as a whole can be too resource-consuming for the hosting hardware. In these kind of situations, `Callback` modules allow to manipulate each single match _on the fly_.

==== `Pre` (or _preprocessing_) modules

Preprocessing is handled by the `Pre` reference class from the `framework.contexts.models` module. To create a `Pre` module, one needs to create a module containing a subclass of `framework.contexts.models.Pre` named `Pre`.

Following is a basic example of a `Pre` module that simply registers the file-based evidence `infected.pdf` for tracking:

[source,python]
----
from framework.contexts import models as _models

class Pre(_models.Pre):
    __author__ = "sk4la"
    __description__ = "Example preprocessing module."
    __license__ = "MIT <https://github.com/sk4la/plast/blob/master/LICENSE.adoc>"
    __maintainer__ = ["sk4la"]
    __system__ = ["Darwin", "Linux", "Windows"]
    __version__ = "0.1"

    def run(self):
        self.case.track_file("/tmp/infected.pdf")
----

`Pre` modules must present a `run` method that will be used as the entry point.

Each `Pre` module corresponds to a positional argument in `plast`. One can add module-wide command-line argument(s) by overriding the `__init__` method like this:

[source,python]
----
from framework.contexts import models as _models
from framework.contexts.logger import Logger as _log

class Pre(_models.Pre):
    __author__ = "sk4la"
    __description__ = "Example preprocessing module."
    __license__ = "MIT <https://github.com/sk4la/plast/blob/master/LICENSE.adoc>"
    __maintainer__ = ["sk4la"]
    __system__ = ["Darwin", "Linux", "Windows"]
    __version__ = "0.1"

    def __init__(self, parser):
        parser.add_argument(
            "-j", "--jobs",
            type=int, 
            default=4, 
            help="number of concurrent job(s)")
        
        parser.add_argument(
            "--debug", 
            default="False", 
            help="run in debug mode")

    def run(self):
        self.case.track_file("/tmp/infected.pdf")

        if self.case.arguments.debug:
            _log.debug("Registering file {}.".format("/tmp/infected.pdf"))
----

The syntax to register command-line arguments is based on the one from the `argparse` module.

Command-line argument(s) are then accessed through the current `Case` instance (see the chapter below to get a grasp on the `Case` class).

==== `Post` (or _postprocessing_) modules

Same as `Pre`, `Post` modules must present themselves as subclasses of the reference `framework.contexts.models.Post` class.

Following is a basic example of a `Post` module that simply prints to the console screen the absolute paths to the matching file-based evidences:

`TODO`

==== `Callback` modules

`TODO`

=== Interacting with the application

==== Case

TODO.

==== Logger

The logger is the main way to interact with the application.

TODO.

==== API

TODO.
