= plast 

`plast` is a modular command-line threat hunting tool & framework.

`plast` uses https://github.com/VirusTotal/yara[`yara`] under the hood through `multiprocessing` tasks to perform rule-based https://en.wikipedia.org/wiki/Indicator_of_compromise[IoC] matching on multiple types of input. 

Input types are defined as `Pre` modules. On rule match, `plast` invokes the selected `Callback` module(s) to immediatelyprocess the current match. It can also invoke `Post` module(s) at the end to perform custom task(s) based on the matching item(s) like formatting or reporting for example. Possibilities are endless.

[ditaa]
----
/----------\       +---------------+                                                    
| Evidence |------>| Preprocessing | `Pre` module                                       
\----------/       +-------+-------+                                                    
   *.zip                   |                                                            
   *.tar                   \                                                [...]       
   *.pst   Decomposed input \               `Callback` module(s)       Dynamic analysis 
   [...]                     \                 /-----------\          /---------------\ 
                             v                 | Callbacks +--------->| Custom action | 
                          +------+    Match    +-----------+          +---------------+ 
           *IoC matching* | YARA +------------>| Callbacks +--------->| Custom action | 
                          +--+---+             +-----------+          +---------------+ 
                             |                                                          
                             |               +----------------+       +---------------+ 
                             \-------------->| Postprocessing +------>| Custom output | 
                                 Match(es)   +----------------+       +---------------+ 
                                             | Postprocessing +------>| Custom output | 
                                             \----------------/       \---------------/ 
                                              `Post` module(s)              *.adoc      
                                                                            *.pdf       
                                                                            *.json      
                                                                            [...]       
----

== Getting Started

Follow these steps to get a copy of the project up and running on a live system.

__This tool must ALWAYS be used in a confined environment.__

=== Prerequisite(s)

`plast` is entirely written in `python3` which makes it compatible with almost all GNU/Linux and macOS distributions. Nevertheless, some minimal dependencies are required.

Follow the steps described below to install the project on the system.

==== Debian-based system

Install the latest `python3` environment:

[source,sh]
----
apt install -y make python3 python3-pip python3-venv
----

`Pre`, `Post` and `Callback` module(s) may have their own dependencies which may not be listed here.

=== Installation

Installing `plast` as a system-wide utility is as simple as:

[source,sh]
----
make
----

To install a developpement environment, issue the following commands:

[source,sh]
----
git clone . $TARGET
cd $TARGET
python3 -m venv .env
source .env/bin/activate
pip install --upgrade pip && pip install -r REQUIREMENTS
----

`$TARGET` represents the working directory where `plast` will be installed.

== Versioning

Refer to the `git` repository to retrieve the latest version.
