= plast - Threat Hunting Tool & Framework [![Python 3.7](https://img.shields.io/badge/python-3.7-yellow.svg)](https://www.python.org/) [![License](https://img.shields.io/badge/license-MIT-red.svg)](https://raw.githubusercontent.com/sk4la/plast/master/LICENSE)

`plast` is a modular command-line threat hunting tool & framework.

`plast` uses https://github.com/VirusTotal/yara[YARA] under the hood through `multiprocessing` tasks to perform rule-based https://en.wikipedia.org/wiki/Indicator_of_compromise[IOC] matching on multiple types of input.

== Getting Started

Follow these steps to get a copy of the project up and running on a live system.

*This tool must ALWAYS be used in a confined environment.*

=== Prerequisite(s)

`plast` is entirely written in `python3` which makes it compatible with almost all GNU/Linux and macOS distributions. Nevertheless, some minimal dependencies are required.

Follow the steps described below to install the project on the system.

==== Debian-based system

Install the `make` package and the latest `python3` environment:

[source,sh]
----
apt install -y make python3 python3-pip python3-venv
----

`Pre`, `Post` and `Callback` modules have their own dependencies which may not be listed here.

=== Installation

Installing `plast` as a system-wide utility is as simple as:

[source,sh]
----
make install
----

It might be necessary to `chmod u+x Makefile` to be able to execute the `make` command.

To install a basic developpement environment, issue the following commands:

[source,sh]
----
git clone . $TARGET
cd $TARGET
python3 -m venv .env
source .env/bin/activate
pip install --upgrade pip && pip install -r REQUIREMENTS
----

`$TARGET` represents the working directory where `plast` will be installed.

== Usage

=== Manual

Use the following command to display the `plast` help menu:

[source,sh]
----
plast [...] --help
----

Each `Pre` module also has a custom help menu that can be called like this:

[source,sh]
----
plast [...] filesystem --help
----

=== Basic examples

The following command will recursively look for every file in the `./case` directory, process them and pass into every registered `Callback` and `Post` module.

[source,sh]
----
plast -o ./out filesystem -i ./case
----

You can easily choose which modules will be invocated during processing by setting the `--callbacks` and `--post` options:

[source,sh]
----
plast -o ./out --callbacks=example --post=example filesystem -i ./case
----

`Callback` and `Post` modules are defined by their basename without extension (ex: `asciidoc` for `asciidoc.py`)

== Contributing

`TODO`

=== Custom modules

`TODO`

==== Preprocessing

`TODO`

==== Postprocessing

`TODO`

==== Callback

`TODO`

== Versioning

Refer to the `git` repository to retrieve the latest version.
