= plast — Threat Hunting Tool & Framework
Nelson "sk4la" Cornet <https://github.com/sk4la>
:caution-caption: :fire:
:uri-org: https://github.com/sk4la
:uri-repo: {uri-org}/plast
:uri-license: {uri-repo}/master/LICENSE
:uri-python: https://www.python.org/
:uri-yara: https://github.com/VirusTotal/yara

image:https://img.shields.io/badge/python-3.7-blue.svg[link={uri-python}] image:https://img.shields.io/badge/license-MIT-green.svg[link={uri-license}]

`plast` is an open-source modular command-line threat hunting tool & framework. It comes with several modules that allow to process multiple data formats, trigger automatic actions upon detection and produce customized output.

Under the hood, `plast` uses {uri-yara}[YARA] through `multiprocessing` tasks to perform rule-based https://en.wikipedia.org/wiki/Indicator_of_compromise[IOC] detection on multiple types of input.

The main goal of the `plast` project is to provide an efficient & effortless way to detect indicators of compomission during incident-response operations.

If provides a comprehensive framework that easily allows processing of multiple data types. It also embeds all modules in one single tool, allowing `plast` to be used on the field as a standalone utility.

`plast` is entirely written in `python3` which makes it compatible with almost all GNU/Linux and macOS distributions. Nevertheless, some minimal dependencies are required.

== Getting Started

Follow these steps to get a copy of the project up and running on a live system.

[CAUTION]
====
This tool must ALWAYS be used in a confined environment.
====

=== Prerequisite(s)

Follow the steps described below to install the project on the system.

==== Debian-based system

Install the `make` package and the latest `python3` environment:

[source,sh]
----
apt install -y make python3 python3-pip python3-venv
----

`Pre`, `Post` and `Callback` modules have their own dependencies which may not be listed here.

=== Installation

Installing `plast` as a system-wide utility is as simple as:

[source,sh]
----
make install
----

It might be necessary to `chmod u+x Makefile` to be able to execute the `make` command.

To install a basic developpement environment, issue the following commands:

[source,sh]
----
git clone {uri-repo}.git plast
cd plast
python3 -m venv .env
source .env/bin/activate
pip install --upgrade pip && pip install -r REQUIREMENTS
----

== Usage

=== Manual

Use the following command to display the `plast` help menu:

[source,sh]
----
plast [...] --help
----

Each `Pre` module also has a custom help menu that can be called like this:

[source,sh]
----
plast [...] filesystem --help
----

=== Basic examples

The following command will recursively look for every file in the `./case` directory, process them and pass into every registered `Callback` and `Post` module.

[source,sh]
----
plast -o ./out filesystem -i ./case
----

You can easily choose which modules will be invocated during processing by setting the `--callbacks` and `--post` options:

[source,sh]
----
plast -o ./out --callbacks=example --post=example filesystem -i ./case
----

`Callback` and `Post` modules are defined by their basename without extension (ex: `asciidoc` for `asciidoc.py`)

== Contributing

`TODO`

=== Custom modules

`TODO`

==== Preprocessing

`TODO`

==== Postprocessing

`TODO`

==== Callback

`TODO`

== Versioning

Refer to the `git` repository to retrieve the latest version.

== Copyright & Licensing

Copyright (c) 2018 Nelson "sk4la" Cornet. Free use of this software is granted under the terms of the MIT license.

See the {uri-license}[LICENSE] file for details.
