= plast — Threat Hunting Tool & Framework
Nelson "sk4la" Cornet <https://github.com/sk4la>
:caution-caption: :fire:
:uri-org: https://github.com/sk4la
:uri-repo: {uri-org}/plast
:uri-raw: https://raw.githubusercontent.com/sk4la/plast
:uri-license: {uri-raw}/master/LICENSE
:uri-python: https://www.python.org
:uri-yara: https://github.com/VirusTotal/yara

image:https://img.shields.io/badge/python-3.7-blue.svg[link={uri-python}] image:https://img.shields.io/badge/license-MIT-green.svg[link={uri-license}]

`plast` is an open-source modular command-line threat hunting tool & framework. It comes with several modules that allow to process multiple data formats, trigger automatic actions upon detection and produce customized output.

Under the hood, `plast` uses {uri-yara}[YARA] through `multiprocessing` tasks to perform rule-based https://en.wikipedia.org/wiki/Indicator_of_compromise[IOC] detection on multiple types of input.

The main goal of the `plast` project is to provide an *efficient & effortless* way to detect indicators of compromission during incident-response operations.

It provides a comprehensive framework that easily allows processing of multiple data types. It also embeds all modules in one single tool, allowing `plast` to be used on the field as a standalone utility.

`plast` is entirely written in `python3` which makes it compatible with almost all GNU/Linux and macOS distributions. Nevertheless, some minimal dependencies are required.

== Getting Started

Follow these steps to get a copy of the project up and running on a live system.

=== Prerequisite(s)

Follow the steps described below to install the project on the system.

==== Debian-based system

Install the required package(s):

[source,sh]
----
apt install -y make
apt install -y python3 python3-pip python3-venv
----

`Pre`, `Post` and `Callback` modules have their own dependencies which may not be listed here.

And the latest `python3` environment:

[source,sh]
----
apt install -y python3 python3-pip python3-venv
----

=== Installation

Installing `plast` as a system-wide utility is as simple as:

[source,sh]
----
make install
----

It might be necessary to `chmod u+x Makefile` to be able to execute the `make` command.

To install a basic developpement environment, issue the following commands:

[source,sh,subs="attributes"]
----
git clone {uri-repo}.git plast
cd plast
python3 -m venv .env
source .env/bin/activate
pip install --upgrade pip && pip install -r REQUIREMENTS
----

== Usage

=== Manual

Use the following command to display the `plast` help menu:

[source,sh]
----
plast [...] --help
----

Each `Pre` module also has a custom help menu that can be called like this:

[source,sh]
----
plast [...] filesystem --help
----

=== Basic examples

The following command will recursively look for every file in the `case` directory, process them and pass into every registered `Callback` and `Post` module.

[source,sh]
----
plast -o out filesystem -i case
----

You can easily choose which modules will be invocated during processing by setting the `--callbacks` and `--post` options:

[source,sh]
----
plast -o out --callbacks=example --post=example filesystem -i case
----

`Callback` and `Post` modules are defined by their basename without extension (ex: `asciidoc` for `asciidoc.py`)

== Contributing

The `plast` project can only be useful if there are modules helping to process custom data formats.

Following this goal, the framework allows to easily integrate new modules by creating custom classes and simply dropping them in the `framework/processors/*` directories. That's it.

=== Custom modules

The core process is handled by three main classes defined in the `framework.contexts.models` module. This module defines:

* The `Pre` reference class;
* The `Post` reference class;
* And the `Callback` reference class.

*A module must be a subclass of one of these reference classes.*

==== Preprocessing

Preprocessing is handled by the `Pre` reference class from the `framework.contexts.models` module. To create a preprocessing module, one needs to create a module containing a subclass of `framework.contexts.models.Pre` named `Pre`.

Following is a basic example of a preprocessing module that registers the file-based evidence `infected.pdf` for tracking:

[source,python]
----
from framework.contexts import models as _models

class Pre(_models.Pre):
    def run(self):
        self.case.track_file("/tmp/infected.pdf")
----

`Pre` modules must have a `run` method to be invocated by the core engine.

Each `Pre` module corresponds to a positional argument in `plast`. One can add command-line argument(s) in the module by overriding the `__init__` method like this:

[source,python]
----
from framework.contexts import models as _models
from framework.contexts.logger import Logger as _log

class Pre(_models.Pre):
    def __init__(self, parser):
        parser.add_argument(
            "-j", "--jobs",
            type=int, 
            default=4, 
            help="number of concurrent job(s)")
        
        parser.add_argument(
            "--debug", 
            default="False", 
            help="run in debug mode")

    def run(self):
        self.case.track_file("/tmp/infected.pdf")

        if self.case.arguments.debug:
            _log.debug("Registering file {}.".format("/tmp/infected.pdf"))
----

The syntax is based on the `argparse` module syntax.

==== Postprocessing

`TODO`

==== Callback

`TODO`

== Versioning

Refer to the `git` repository to retrieve the latest version.

== Copyright & Licensing

Copyright (c) 2018 Nelson "sk4la" Cornet. Free use of this software is granted under the terms of the MIT license.

See the {uri-license}[LICENSE] file for details.
